### PR TITLE
Fix issue with URL links picking up trailing quotes (fixes #816)

### LINKED ISSUE #816: hyperlink address in response includes trailing double quote (version 0.24.5)
My JSON response contains download links for files like
{
  ...
  "url": "https://path/to/file.ext"
}

RestClient v0.24.5 creates a hyperlink from it with the following target address:
  https://path/to/file.ext"
When I click the hyperlink, it won't resolve because of the trailing double quote added by RestClient.

In v0.24.4 this worked fine. RestClient created target address as expected:
  https://path/to/file.ext

### PR DESCRIPTION
**Pull request by adibradfield**
An update to highlight.js means that it has now started escaping quotes, which has broken the regex that is used to find and replace urls. This PR adds additional logic to remove the encoded characters from the link that gets generated

### CODE REVIEW

File: src/views/httpResponseWebview.ts [hunk 1]
```diff
@@ -353,7 +353,22 @@ ${HttpResponseWebview.formatHeaders(response.headers)}`;
     }
 
     private addUrlLinks(innerHtml: string) {
-        return innerHtml.replace(this.urlRegex, '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>');
+        return innerHtml.replace(this.urlRegex, (match: string): string => {
+            const encodedEndCharacters = ["&lt;","&gt;","&quot;","&apos;"];
+            let urlEndPosition = match.length;
+
+            encodedEndCharacters.forEach((char) => {
+                var index = match.indexOf(char);
```
Comment (Huachao) [inline src/views/httpResponseWebview.ts:361]: use `let` or `const` over `var`

File: src/views/httpResponseWebview.ts [hunk 2]
```diff
@@ -353,7 +353,22 @@ ${HttpResponseWebview.formatHeaders(response.headers)}`;
...
+                if(index > -1 && index < urlEndPosition){
+                    urlEndPosition = index;
```
Comment (Huachao) [inline src/views/httpResponseWebview.ts:363]: is it just simply
```js
if (index !== -1)
```

File: src/views/httpResponseWebview.ts [hunk 3]
```diff
@@ -353,7 +353,22 @@ ${HttpResponseWebview.formatHeaders(response.headers)}`;
     }
 
     private addUrlLinks(innerHtml: string) {
-        return innerHtml.replace(this.urlRegex, '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>');
```
Comment (Huachao) [inline src/views/httpResponseWebview.ts:356]: Can we do this directly in the `urlRegex`?

**Review by Huachao — CHANGES_REQUESTED** [review]

**Review by Huachao — APPROVED** [review]

**Comment by Huachao** [comment]
@adibradfield Merged, thanks
